apiVersion: v1
description: A Helm chart for Elasticsearch operator
name: elasticsearch-operator
version: 0.1.3
sources:
- https://github.com/upmc-enterprises/elasticsearch-operator
maintainers:
- name: komljen
  email: alen.komljen@live.com
  url: https://akomljen.com
