apiVersion: v1
description: A Helm chart for Elasticsearch cluster
name: elasticsearch
version: 0.1.2
sources:
- https://github.com/upmc-enterprises/elasticsearch-operator
maintainers:
- name: komljen
  email: alen.komljen@live.com
  url: https://akomljen.com
